set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_TOOLCHAIN_PATH "/opt/llvm-mingw/llvm-mingw-ucrt/")

set(CMAKE_C_COMPILER "${CMAKE_TOOLCHAIN_PATH}/bin/x86_64-w64-mingw32-clang")
set(CMAKE_CXX_COMPILER "${CMAKE_TOOLCHAIN_PATH}/bin/x86_64-w64-mingw32-clang++")
set(CMAKE_RC_COMPILER  "${CMAKE_TOOLCHAIN_PATH}/bin/x86_64-w64-mingw32-windres")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_TOOLCHAIN_PATH}/generic-w64-mingw32/include")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_EXE_LINKER_FLAGS "-static" CACHE STRING "" FORCE)

